GET http://localhost:5078/Funcionario


GET http://localhost:5078/Funcionario/1


POST http://localhost:5078/Funcionario
Content-Type: application/json

{
  "nome": "Maria Silva",
  "cpf": "123.456.789-00",
  "cargo": "Gerente",
  "dataContratacao": "2023-01-01T00:00:00",
  "salario": 5000,
  "endereco": "Rua das Flores, 100",
  "telefone": "99999-9999"
}

###
PUT http://localhost:5078/Funcionario/1
Content-Type: application/json

{
  "id": 2,
  "nome": "Maria Silva",
  "cpf": "123.456.789-00",
  "cargo": "Diretora",
  "dataContratacao": "2023-01-01T00:00:00",
  "salario": 7000,
  "endereco": "Rua das Flores, 100",
  "telefone": "99999-9999"
}

###
DELETE http://localhost:5078/Funcionario/1
